# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt3-examples-1',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/gpt3-examples-1',
                'lib_path': 'gpt3_examples_1'},
  'syms': {'gpt3_examples_1.examples': {'gpt3_examples_1.examples.ask_gpt3': ('examples.html#ask_gpt3', 'gpt3_examples_1/examples.py')}}}