# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_examples.ipynb.

# %% auto 0
__all__ = ['ask_gpt3']

# %% ../nbs/00_examples.ipynb 3
from nbdev.showdoc import *
import openai
from api_secrets import API_KEY
openai.api_key = API_KEY

# %% ../nbs/00_examples.ipynb 12
def ask_gpt3(prompt,openai=openai):
    response = openai.Completion.create(engine="text-davinci-001", prompt=prompt, max_tokens=20)
    text_response = str(response["choices"][0]["text"])[2:]
    return text_response
